from __future__ import annotations

from enum import Enum


class ActionType(Enum):
    OPEN_APP = "open_app"
    CLOSE_APP = "close_app"
    PLAY_SPOTIFY = "play_spotify"
    SEARCH_WEB = "search_web"

    DISCORD_OPEN = "discord_open"
    DISCORD_CLOSE = "discord_close"
    DISCORD_FOCUS = "discord_focus"
    DISCORD_OPEN_DM = "discord_open_dm"
    DISCORD_OPEN_SERVER = "discord_open_server"
    DISCORD_OPEN_CHANNEL = "discord_open_channel"
    DISCORD_SEND_MESSAGE = "discord_send_message"
    DISCORD_REPLY_CURRENT = "discord_reply_current"
    DISCORD_TOGGLE_MUTE = "discord_toggle_mute"
    DISCORD_TOGGLE_DEAFEN = "discord_toggle_deafen"
    DISCORD_JOIN_VOICE = "discord_join_voice"
    DISCORD_LEAVE_VOICE = "discord_leave_voice"
    DISCORD_SET_STATUS = "discord_set_status"
    DISCORD_PREVIOUS = "discord_previous"

    BROWSER_OPEN = "browser_open"
    BROWSER_CLOSE = "browser_close"
    BROWSER_FOCUS = "browser_focus"
    BROWSER_OPEN_SITE = "browser_open_site"
    BROWSER_OPEN_URL = "browser_open_url"
    BROWSER_SEARCH_GOOGLE = "browser_search_google"
    BROWSER_SEARCH_YOUTUBE = "browser_search_youtube"
    BROWSER_SEARCH_IMAGES = "browser_search_images"
    BROWSER_SEARCH_NEWS = "browser_search_news"
    BROWSER_NEW_TAB = "browser_new_tab"
    BROWSER_CLOSE_TAB = "browser_close_tab"
    BROWSER_NEXT_TAB = "browser_next_tab"
    BROWSER_PREV_TAB = "browser_prev_tab"
    BROWSER_BACK = "browser_back"
    BROWSER_FORWARD = "browser_forward"
    BROWSER_RELOAD = "browser_reload"
    BROWSER_OPEN_EMAIL = "browser_open_email"
    BROWSER_CHECK_UNREAD = "browser_check_unread"
    BROWSER_SEARCH_EMAIL_FROM = "browser_search_email_from"
    BROWSER_SEARCH_EMAIL_SUBJECT = "browser_search_email_subject"
