from __future__ import annotations

DEFAULT_LANGUAGE = "pt-BR"

_STRINGS: dict[str, dict[str, str]] = {
    "pt-BR": {
        "window_title": "Jarvis",
        "title": "JARVIS",
        "subtitle": "modo local · qwen 2.5",
        "response_idle": "Sistema online.",
        "system_online": "Sistema online. Em que posso ajudar, senhor?",
        "debug_user_prefix": "você",
        "debug_jarvis_prefix": "jarvis",
        "ready": "Pronto",
        "listening": "Ouvindo",
        "processing": "Processando",
        "empty_transcript": "Não consegui entender o pedido, senhor.",
        "could_not_catch": "Não consegui ouvir, senhor.",
        "command_ok": "Entendido, senhor.",
        "command_not_found": "Aplicativo não encontrado, senhor.",
        "ack_open_app": "Abrindo {target}, senhor.",
        "ack_close_app": "Fechando {target}, senhor.",
        "ack_play_spotify": "Tocando {target} no Spotify, senhor.",
        "ack_search_web": "Pesquisando {target}, senhor.",
        "ack_discord_open": "Abrindo o Discord, senhor.",
        "ack_discord_close": "Fechando o Discord, senhor.",
        "ack_discord_focus": "Focando o Discord, senhor.",
        "ack_discord_open_dm": "Abrindo a conversa com {label}, senhor.",
        "ack_discord_open_server": "Abrindo o servidor {label}, senhor.",
        "ack_discord_open_channel": "Abrindo o canal {label}, senhor.",
        "ack_discord_send_message": "Mandando a mensagem para {label}, senhor.",
        "ack_discord_reply_current": "Respondendo agora, senhor.",
        "ack_discord_toggle_mute": "Alterando o microfone, senhor.",
        "ack_discord_toggle_deafen": "Alterando o áudio, senhor.",
        "ack_discord_join_voice": "Entrando na call {label}, senhor.",
        "ack_discord_leave_voice": "Saindo da call, senhor.",
        "ack_discord_set_status": "Atualizando seu status, senhor.",
        "ack_discord_previous": "Voltando para o canal anterior, senhor.",
        "ack_browser_open": "Abrindo o navegador, senhor.",
        "ack_browser_close": "Fechando o navegador, senhor.",
        "ack_browser_focus": "Focando o navegador, senhor.",
        "ack_browser_open_site": "Abrindo {label}, senhor.",
        "ack_browser_open_url": "Abrindo o endereço, senhor.",
        "ack_browser_search_google": "Pesquisando {label}, senhor.",
        "ack_browser_search_youtube": "Buscando {label} no YouTube, senhor.",
        "ack_browser_search_images": "Buscando imagens de {label}, senhor.",
        "ack_browser_search_news": "Buscando notícias de {label}, senhor.",
        "ack_browser_new_tab": "Abrindo uma nova aba, senhor.",
        "ack_browser_close_tab": "Fechando a aba, senhor.",
        "ack_browser_next_tab": "Próxima aba, senhor.",
        "ack_browser_prev_tab": "Aba anterior, senhor.",
        "ack_browser_back": "Voltando, senhor.",
        "ack_browser_forward": "Avançando, senhor.",
        "ack_browser_reload": "Recarregando, senhor.",
        "ack_browser_open_email": "Abrindo seu email, senhor.",
        "ack_browser_check_unread": "Verificando emails não lidos, senhor.",
        "ack_browser_search_email_from": "Buscando emails de {label}, senhor.",
        "ack_browser_search_email_subject": "Buscando emails sobre {label}, senhor.",
        "ack_show_off": "Observe, senhor.",
        "no_response": "Não tenho uma resposta para isso agora, senhor.",
        "date_answer": "Hoje é {date}, senhor.",
        "time_answer": "Agora são {time}, senhor.",
        "weather_unavailable": "Não consigo verificar o clima sem acesso à internet, senhor.",
        "greeting": "Olá, senhor. Em que posso ajudar?",
        "how_are_you": "Estou funcional e pronto para servir, senhor.",
        "who_are_you": "Sou o Jarvis, seu assistente pessoal de desktop, senhor.",
        "thanks": "Às ordens, senhor.",
        "goodbye": "Até logo, senhor.",
        "help": "Posso abrir e fechar aplicativos, informar a hora, a data e responder perguntas, senhor.",
        "joke": "Por que o programador confundiu Halloween com Natal? Porque 31 OCT é igual a 25 DEC, senhor.",
        "fallback_unknown": "Às ordens, senhor.",
        "confirm_candidate": "Você quis dizer {candidate}, senhor?",
        "confirmation_cancelled": "Entendido, senhor. Me diga de novo, por favor.",
        "confirmation_confirmed": "Perfeito, senhor.",
    },
    "en-US": {
        "window_title": "Jarvis",
        "title": "JARVIS",
        "subtitle": "local mode · qwen 2.5",
        "response_idle": "System online.",
        "system_online": "System online. How may I assist you, sir?",
        "debug_user_prefix": "you",
        "debug_jarvis_prefix": "jarvis",
        "ready": "Ready",
        "listening": "Listening",
        "processing": "Processing",
        "empty_transcript": "I could not understand the request, sir.",
        "could_not_catch": "I couldn't catch that, sir.",
        "command_ok": "Understood, sir.",
        "command_not_found": "Application not found, sir.",
        "ack_open_app": "Opening {target}, sir.",
        "ack_close_app": "Closing {target}, sir.",
        "ack_play_spotify": "Playing {target} on Spotify, sir.",
        "ack_search_web": "Searching {target}, sir.",
        "ack_discord_open": "Opening Discord, sir.",
        "ack_discord_close": "Closing Discord, sir.",
        "ack_discord_focus": "Focusing Discord, sir.",
        "ack_discord_open_dm": "Opening DM with {label}, sir.",
        "ack_discord_open_server": "Opening server {label}, sir.",
        "ack_discord_open_channel": "Opening channel {label}, sir.",
        "ack_discord_send_message": "Sending the message to {label}, sir.",
        "ack_discord_reply_current": "Replying now, sir.",
        "ack_discord_toggle_mute": "Toggling microphone, sir.",
        "ack_discord_toggle_deafen": "Toggling audio, sir.",
        "ack_discord_join_voice": "Joining voice channel {label}, sir.",
        "ack_discord_leave_voice": "Leaving voice channel, sir.",
        "ack_discord_set_status": "Updating your status, sir.",
        "ack_discord_previous": "Switching to previous channel, sir.",
        "ack_browser_open": "Opening the browser, sir.",
        "ack_browser_close": "Closing the browser, sir.",
        "ack_browser_focus": "Focusing the browser, sir.",
        "ack_browser_open_site": "Opening {label}, sir.",
        "ack_browser_open_url": "Opening the address, sir.",
        "ack_browser_search_google": "Searching {label}, sir.",
        "ack_browser_search_youtube": "Searching {label} on YouTube, sir.",
        "ack_browser_search_images": "Searching images of {label}, sir.",
        "ack_browser_search_news": "Searching news about {label}, sir.",
        "ack_browser_new_tab": "New tab, sir.",
        "ack_browser_close_tab": "Closing tab, sir.",
        "ack_browser_next_tab": "Next tab, sir.",
        "ack_browser_prev_tab": "Previous tab, sir.",
        "ack_browser_back": "Going back, sir.",
        "ack_browser_forward": "Going forward, sir.",
        "ack_browser_reload": "Reloading, sir.",
        "ack_browser_open_email": "Opening your email, sir.",
        "ack_browser_check_unread": "Checking unread email, sir.",
        "ack_browser_search_email_from": "Searching emails from {label}, sir.",
        "ack_browser_search_email_subject": "Searching emails about {label}, sir.",
        "ack_show_off": "Observe, sir.",
        "no_response": "I do not have a response for that right now, sir.",
        "date_answer": "Today is {date}, sir.",
        "time_answer": "It is currently {time}, sir.",
        "weather_unavailable": "I cannot check weather without internet access, sir.",
        "greeting": "Hello, sir. How can I help you?",
        "how_are_you": "I am functional and ready to serve, sir.",
        "who_are_you": "I am Jarvis, your personal desktop assistant, sir.",
        "thanks": "At your service, sir.",
        "goodbye": "Goodbye, sir.",
        "help": "I can open and close applications, tell the time and date, and answer questions, sir.",
        "joke": "Why did the programmer confuse Halloween with Christmas? Because 31 OCT equals 25 DEC, sir.",
        "fallback_unknown": "At your service, sir.",
        "confirm_candidate": "Did you mean {candidate}, sir?",
        "confirmation_cancelled": "Understood, sir. Please tell me again.",
        "confirmation_confirmed": "Perfect, sir.",
    },
}


class Strings:
    def __init__(self, language: str = DEFAULT_LANGUAGE) -> None:
        self._language = language if language in _STRINGS else DEFAULT_LANGUAGE

    @property
    def language(self) -> str:
        return self._language

    def get(self, key: str, **kwargs: str) -> str:
        template = _STRINGS[self._language].get(key) or _STRINGS[DEFAULT_LANGUAGE].get(key, key)
        return template.format(**kwargs) if kwargs else template
