from __future__ import annotations

from typing import Protocol


class IBrowserController(Protocol):
    """Low-level driver: opens URLs in the default browser and dispatches
    tab/navigation hotkeys to whichever browser window is focused.

    A Protocol (not ABC) so tests can pass a plain spy without inheritance.
    """

    def open_url(self, url: str, new_tab: bool = True) -> bool: ...

    def close_browser(self) -> bool: ...

    def focus_window(self) -> bool: ...

    def hotkey_new_tab(self) -> None: ...

    def hotkey_close_tab(self) -> None: ...

    def hotkey_next_tab(self) -> None: ...

    def hotkey_prev_tab(self) -> None: ...

    def hotkey_back(self) -> None: ...

    def hotkey_forward(self) -> None: ...

    def hotkey_reload(self) -> None: ...
